### PR TITLE
Exclude disabled agents from Agent Diagram and add a toggle button

### PR DESCRIPTION
**Pull request by knu**
I think it's a good idea to keep an agent for later reference or cloning even after it has served its purpose, so I usually just disable agents rather than deleting them.  However, a growing number of disabled agents get in the way of getting a whole picture of what is actually/actively being done by Huginn.

So, what about making it optional to draw disabled agents in an Agent diagram?

### CODE REVIEW

**Comment by cantino** [comment]
Seems like a good idea.  I wonder if it should show disabled by default when you have fewer than, say, 10 disabled Agents?

**Comment by knu** [comment]
@cantino I agree that the number of omitted agents matters to users, so I've tweak it a bit as above.    Does it seem fair to you?

**Comment by cantino** [comment]
Yea, that seems good.  We could also consider always showing disabled agents if fewer than 10 exist, or something.

**Comment by knu** [comment]
OK, I'll make it not hide disabled agents by default then.  I'd prefer the behavior to be deterministic.

**Comment by cantino** [comment]
Looks good!

**Pull request merged**
