### PR TITLE
Create twitter_favorite Agent

### PR DESCRIPTION
**Pull request by bigretromike**
Agent that returns favorite tweet of given user

### CODE REVIEW

**Comment by cantino** [comment]
Nice @michal-polrolniczak! Do you think this should be combined with the `TwitterUserAgent`? You could add `include_favorites` to that Agent using the code you've already written.

**Comment by michal-polrolniczak** [comment]
Hello @cantino thanks for warm welcome!
No, I don't think so. I'm right now updating it to use some kind of buffer, because from what I see when you fav tweet you see it with original date, not date you fav it, so it wont trigger Agent. I'm working to make a buffer with history of last ex. 100 fav post so you wont crawl them again and you wont miss fav you did on tweets you missed.
I hope you get the point.

In the end that could be merge but for now lets keep them separate ;)

Is there a way to change memory inside Agent from Hash to Array, because that would cut the time needed to flush old data from buffer, or maybe there is a way to make my own "memory" object for Agent?

Also from Twitter API doc using list_fav is limited with bigger limit than user tweets.

**Comment by cantino** [comment]
You can store anything you want in the values of `memory`, so you could say `memory[:list] ||= []` and then start using `memory[:list]` as an array.  `memory` is just a hash this is persisted for you.

We make a similar list called `memory[:seen_ids]` in the RssAgent.

**Comment by michal-polrolniczak** [comment]
Hope you will include this Agent to main repo, so more people could transfer from IFTTT solution to Open Source one :+1: 
Using this agent helped me with few things that was impossible with ifttt/pipes :-)

**Comment by cantino** [comment]
Thanks @michal-polrolniczak!  Would you mind adding some RSpec specs for this new Agent as well?  We have some decent examples in the repo, and #1076 has some new ones too for another Twitter agent.

**Comment by michal-polrolniczak** [comment]
@cantino, I would like to say that "no problem" but from what I see I don't have idea how to do it. This is my first Ruby copy-paste script, and that RSpec is just over me right now. From what I read it is not essential but useful. I maybe try to overcome this one, but I wont mind if someone do first one for me :+1:

**Comment by cantino** [comment]
It's not bad :).  Run `rspec spec/models/agents/twitter_search_agent_spec.rb` for example.  That spec was just added and yours would be very similar.

**Comment by michal-polrolniczak** [comment]
If you say so, but after installing rspec via ```gem install rspec``` and using it I get this

```/home/huginn/huginn (git)-[master] # rspec spec/models/agents/twitter_search_agent_spec.rb
/usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- coveralls (LoadError)
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/huginn/huginn/spec/spec_helper.rb:7:in `<top (required)>'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/huginn/huginn/spec/models/agents/twitter_search_agent_spec.rb:1:in `<top (required)>'
        from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `load'
        from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `block in load_spec_files'
        from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1325:in `each'
        from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1325:in `load_spec_files'
        from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:102:in `setup'
        from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:88:in `run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
        from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/exe/rspec:4:in `<top (required)>'
        from /usr/local/bin/rspec:23:in `load'
        from /usr/local/bin/rspec:23:in `<main>'```

**Comment by michal-polrolniczak** [comment]
I had to install:
```gem install coveralls
gem install term-ansicolor
```

But that didnt fix problem:
```
/usr/local/lib/ruby/gems/2.2.0/gems/coveralls-0.8.3/lib/coveralls/output.rb:63:in `require': cannot load such file -- term/ansicolor (LoadError)
        from /usr/local/lib/ruby/gems/2.2.0/gems/coveralls-0.8.3/lib/coveralls/output.rb:63:in `format'
        from /usr/local/lib/ruby/gems/2.2.0/gems/coveralls-0.8.3/lib/coveralls/output.rb:90:in `puts'
        from /usr/local/lib/ruby/gems/2.2.0/gems/coveralls-0.8.3/lib/coveralls/simplecov.rb:82:in `display_error'
        from /usr/local/lib/ruby/gems/2.2.0/gems/coveralls-0.8.3/lib/coveralls/simplecov.rb:78:in `rescue in format'
        from /usr/local/lib/ruby/gems/2.2.0/gems/coveralls-0.8.3/lib/coveralls/simplecov.rb:31:in `format'
        from /usr/local/lib/ruby/gems/2.2.0/gems/simplecov-0.10.0/lib/simplecov/result.rb:46:in `format!'
        from /usr/local/lib/ruby/gems/2.2.0/gems/simplecov-0.10.0/lib/simplecov/configuration.rb:159:in `block in at_exit'
        from /usr/local/lib/ruby/gems/2.2.0/gems/simplecov-0.10.0/lib/simplecov/defaults.rb:60:in `call'
        from /usr/local/lib/ruby/gems/2.2.0/gems/simplecov-0.10.0/lib/simplecov/defaults.rb:60:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:34:in `block in setup': You have already activated json 1.8.1, but your Gemfile requires json 1.8.3. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
        from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:19:in `setup'
        from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:127:in `setup'
        from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/setup.rb:8:in `<top (required)>'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /home/huginn/huginn/config/boot.rb:6:in `<top (required)>'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/huginn/huginn/config/application.rb:1:in `<top (required)>'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/huginn/huginn/config/environment.rb:2:in `<top (required)>'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/huginn/huginn/spec/spec_helper.rb:11:in `<top (required)>'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/huginn/huginn/spec/models/agents/twitter_search_agent_spec.rb:1:in `<top (required)>'
        from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `load'
        from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `block in load_spec_files'
        from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1325:in `each'
        from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1325:in `load_spec_files'
        from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:102:in `setup'
        from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:88:in `run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
        from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/exe/rspec:4:in `<top (required)>'
        from /usr/local/bin/rspec:23:in `load'
        from /usr/local/bin/rspec:23:in `<main>'
```

So yeah :-) hard start with that rspec thing

**Comment by cantino** [comment]
Run `bundle install` and then `bundle exec rspec ...`.  Do you still get that error?

**Comment by cantino** [comment]
It looks like `Twitter::REST::Favorites.favorites` can take a `since_id` just like the `user_timeline` method can.  Does this not work in this case?  It'd be nice if it did, because then we could just modify the `TwitterUserAgent` to have a `mode` of either `timeline` or `favorites`.

**Comment by bigretromike** [comment]
from what I remamber no it dosn't its not clean properly, I using it all the time In the way its now and its work perfect fine :+1: If you like to you can merge those - I just made it work

**Comment by cantino** [comment]
I'm going to re-open this so that if someone else wants to add specs and get this mergable, they can.

**Comment by Jngai** [comment]
I will try to add the specs.

**Comment by cantino** [comment]
Thanks!

**Comment by Jngai** [comment]
#1310

**Comment by cantino** [comment]
Replaced by #1310.

**Comment by bigretromike** [comment]
Great job guys!

**Pull request closed without merging**
