### PR TITLE
Do not try to load .env file on heroku

### LINKED ISSUE #1178: Build for Heroku fails
I'm a noob at Heroku and ruby. I'm getting the following from both the readme button deploy and by running setup_heroku from my local environment. I'm on a mac, have huggin running fine locally. Not sure if this helps, but my local environment wouldn't work until I ran bundle update. Not sure if by doing that it updated something that wasn't planned for. My local .env file looks fine to me - I've also tried a copy of the template with no changes and I get the same error.Anyhow, any help is appreciated. Here's the error from setup_heroku (substituted "hex" for tmp directory name in a couple of spots):

> -----> Fetching set buildpack https://github.com/heroku/heroku-buildpack-multi.git... done
> -----> Multipack app detected
> =====> Downloading Buildpack: https://github.com/cantino/heroku-selectable-procfile.git
> =====> Detected Framework: Selectable Procfile
> -----> Using deployment/heroku/Procfile.heroku as Procfile
> =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-ruby.git
> =====> Detected Framework: Ruby
> -----> Compiling Ruby/Rails
> sh: 2: Syntax error: Unterminated quoted string
>  !
>  !     There was an error parsing your Gemfile, we cannot continue
>  !     Could not load huginn settings from .env file.
>  !     
>  !     Make sure to copy the .env.example to .env and change it to match your configuration.
>  !     
>  !     Capistrano 2 users: Make sure shared files are symlinked before bundle runs: before 'bundle:install', 'deploy:symlink_configs'
>  !     /tmp/build_hex/cantino-huginn-f49ef15/lib/gemfile_helper.rb:25:in `sanity_check': Could not load huginn settings from .env file. (RuntimeError)
>  !     /tmp/build_hex/cantino-huginn-f49ef15/lib/gemfile_helper.rb:13:in `load_dotenv'
>  !     /tmp/build_hex/cantino-huginn-f49ef15/Gemfile:8:in `eval_gemfile'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/dsl.rb:32:in `instance_eval'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/dsl.rb:32:in `eval_gemfile'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/dsl.rb:10:in `evaluate'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/definition.rb:25:in `build'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler.rb:155:in `definition'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/cli/check.rb:11:in `run'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/cli.rb:103:in `check'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/cli.rb:10:in `start'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/bin/bundle:20:in `block in <top (required)>'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/bin/bundle:18:in `<top (required)>'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/bin/bundle:23:in `load'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/bin/bundle:23:in `<main>'
>  !     There was an error in your Gemfile, and Bundler cannot continue.
>  !
>  !     Push rejected, failed to compile Multipack app

### PR DESCRIPTION
**Pull request by dsander**
Fixes  #1178

### CODE REVIEW

**Comment by cantino** [comment]
LGTM.  Does this let you deploy to Heroku?

**Comment by dsander** [comment]
I was not able to point the deploy button to my repository for whatever reason, but a manual `heroku push` deploy worked.

**Comment by cantino** [comment]
Nice.  Let's get it out and then try the button, I guess?

**Comment by dsander** [comment]
Agreed.

**Comment by dsander** [comment]
Deployment went well, added one line (490c51af057e5f7f8e8350db14271749ed8c20f6)  to the post deploy instructions.

**Comment by cantino** [comment]
Nice, thanks for fixing!

**Pull request merged**
