### PR TITLE
Upgrade Liquid to 3

### PR DESCRIPTION
**Pull request by knu**
It has nice new filters such as `default`, `strip`, `uniq`, etc.

### CODE REVIEW

**Comment by cantino** [comment]
Awesome!  Do you think this will break anything for folks?  Is it backwards-compatible?

**Comment by knu** [comment]
It should be, considering the user base of Shopify.  I think the reason for the major bump to 3 was the dropped support for Ruby 1.8, like in Liquid 4 support for 1.9 will be dropped.

**Comment by cantino** [comment]
That makes sense.  You've tried it in your deployment and it seems to work well?

**Comment by knu** [comment]
I've been running this for a couple days without a problem.  Any other takers? :D

**Comment by cantino** [comment]
@dsander ^

**Comment by dsander** [comment]
Deployed to production, lets see how it goes :smile:

**Comment by knu** [comment]
@dsander How's is going?  For me there have been no problem so far.

**Comment by dsander** [comment]
@knu Very good, by now probably all my agents that use liquid have triggered at least once. 

:+1: Especially happy that we finally have that bundler footer in the Gemfile, switching branches has been a pain lately

**Comment by knu** [comment]
Thanks for testing!

**Pull request merged**
