### PR TITLE
Fix support for postgresql adapter in Docker container

### PR DESCRIPTION
**Pull request by pka**
For running the docker container with my PostgreSQL DB, I had to change the adapater name and add the 'pg' gem to Gemfile. Not tested on Heroku.

### CODE REVIEW

**Comment by cantino** [comment]
@dsander, this seems to align with some changes you've made, although we could replace ON_HEROKU with something better to make this cleaner.

**Comment by cantino** [comment]
Thanks @pka!

**Comment by dsander** [comment]
@cantino It does, with #1040 we could just set `DATABASE_ADAPTER = postgresql` and maybe add `WANTS_12FACTOR` for heroku.

**Comment by cantino** [comment]
@dsander, would you mind reviewing the state of this?

**Comment by dsander** [comment]
The docker image definitely work with postgres now, this got superseded by one with the docker improvement PR. Thanks for working on it @pka!

**Pull request closed without merging**
