### PR TITLE
Updated Gemfile with latest tumblr

### PR DESCRIPTION
**Pull request by spdustin**
Earlier fork of tumblr has been merged and deleted; this commit points the Gemfile to the official tumblr-client that includes the previous forked version's fix for faraday_middleware

### CODE REVIEW

**Comment by spdustin** [comment]
@knu deleted his patch-1 fork earlier today. It was merged into [tumblr/tumblr_client](https://github.com/tumblr/tumblr_client) three weeks ago.

**Comment by spdustin** [comment]
Whoops, hold off on that, sorry...

**Comment by spdustin** [comment]
Ha, I must not have refreshed my browser before #1094 - Let's see who wins the Travis race :grin:

**Comment by JesterEE** [comment]
Ha, both of ours did!  But I your patch is probably better since it's pulling the fixing commit and not master.  Not sure how to fix those errors, so I'll leave it up to you ;).

**Comment by spdustin** [comment]
I'm closing this PR and issuing another one that updates the rspec config to fix Travis build failures. Incoming...

**Pull request closed without merging**
