### PR TITLE
Docker supervisord

### PR DESCRIPTION
**Pull request by ianblenke**
This remedies the problem with jobs not starting up, fixes a few bugs with environment variable handling, and runs an exec'ed supervisord so it can handle all of the signals and children processes appropriately.

### CODE REVIEW

**Comment by cantino** [comment]
(CC #680)

**Comment by cantino** [comment]
Awesome, thanks @ianblenke!  @TFenby, would you mind seeing if this fixes your issue?

**Comment by TFenby** [comment]
Woah. That was quick. I'll check it out right now.

**Comment by TFenby** [comment]
This does solve this issue of the jobs not running. Thanks a lot, guys.

**Comment by cantino** [comment]
Are there README changes that need to be made for https://registry.hub.docker.com/u/cantino/huginn/ ?

**Comment by TFenby** [comment]
I wouldn't think so, but @ianblenke should probably verify that.

**Comment by ianblenke** [comment]
There should be no new functionality introduced in this PR, it is entirely bug fixes. I should be ashamed of the state of the docker container prior to this, to be honest.

**Comment by cantino** [comment]
Thanks @ianblenke!  I forget, after merging, do I also need to update anything in Docker Hub?

**Comment by ianblenke** [comment]
Nope, you have auto-build enabled for all commits. As soon as you merged it, that triggered a Docker Hub build here: https://registry.hub.docker.com/u/cantino/huginn/build_id/18004/code/bwpjqq5k6yb7ulgoxd9wmay/

**Pull request merged**
