### PR TITLE
Use the XPath expression `string(.)` instead of `.//text()`

### PR DESCRIPTION
**Pull request by knu**
That is the correct way to extract a raw string with all text nodes concatenated without entity escaping.

I think I still have lots to learn...

### CODE REVIEW

**Comment by K1773R** [comment]
What exactly is the different here? Examples?
I've been using .//text() in a lot of places without any issues so far.

**Comment by knu** [comment]
The difference is entity escaping.  You can see that from the updated specs.

**Comment by knu** [comment]
`.//text` extracts a set of text nodes, so the result will be those stringified as HTML/XML.  On the other hand, `string(.)` returns a string value of the selected node, which is a raw, unescaped text.

**Comment by cantino** [comment]
Looks good! I didn't know this either.

**Pull request merged**
