### PR TITLE
added avatar to scenario

### PR DESCRIPTION
**Pull request by Jngai**

### CODE REVIEW

**Comment by Jngai** [comment]
#752

**Comment by Jngai** [comment]
@cantino I think this answered most of the issue that was requested. Will you confirm that this answers the issue? Basically I am just using paperclip to mount avatar on scenario model. Will add spec later.

**Comment by dsander** [comment]
Paperclip is a pretty big dependency and we would need to store the image in the database to support docker and heroku, would improving the current scenario label be an option? For example the "Morning digest" scenario could use "MD" as a label instead of the generic "A".

**Comment by Jngai** [comment]
The generic A is a glyph from bootstrap so its just html. I guess it depends if the other option answers the issue requested. I will put this on hold for now.

**Comment by virtadpt** [comment]
If the sizes of the icons were rigorously enforced - 64x64, say - and resized before storage in the database, what sort of bloat might be expected?

Obviously, if a Huginn instance has dozens upon dozens of scenarios that table's going to get pretty big, but for a reasonably sized instance (a dozen or two) I don't think it would be onerous.

**Comment by Jngai** [comment]
There is also carrierwave instead of paperclip. I am not sure about the dependency though.

**Comment by cantino** [comment]
This look like good work @Jngai.

However, I agree that both carrierwave and paperclip are big dependencies to add for this feature.  Could we use font-awesome and a dropdown menu to allow users to select a glyph instead?  (We always include `font-awesome-sass` and `select2-rails` in the Gemfile.)

**Pull request closed without merging**
