### PR TITLE
.env: fix RAILS_ENV for docker

### PR DESCRIPTION
**Pull request by xu-cheng**
Otherwise, `HUGINN_RAILS_ENV` won't take affect for docker installation.

### CODE REVIEW

**Comment by dsander** [comment]
Thanks @xu-cheng, did you successfully run the docker container in the production environment? Last time I checked there were a few issues related to the assets not being precompiled.

**Comment by xu-cheng** [comment]
> did you successfully run the docker container in the production environment?

I haven't checked this yet. Without this fix, I was unable to run docker as production. This value keeps getting overwritten by init script.

**Comment by dsander** [comment]
That makes sense, you can build the docker container locally, the git repository and branch needs to be changed to `git clone --depth 1 https://github.com/xu-cheng/huginn -b rails-env-docker /app` [here](https://github.com/cantino/huginn/blob/master/docker/scripts/setup#L5)
Running `docker build --rm=false -t huginn-test . && docker run -it -p 3000:3000 huginn-test` in the `docker` subdirectory should then build and run the image.

**Comment by dsander** [comment]
With #1204 merged the docker images run in the production environment by default.

**Pull request closed without merging**
