### PR TITLE
Fix missing scenario clone

### PR DESCRIPTION
**Pull request by thiagotalma**

### CODE REVIEW

**Comment by dsander** [comment]
Not sure if that was intensional, but I don't feel strongly about it. @cantino do you agree?

@thiagotalma Could you add a test that ensures cloned agents retain the scenarios of the original agent?

**Comment by cantino** [comment]
I'm not sure.  @knu, was this intentional?

**Comment by knu** [comment]
I don't know.  Doesn't the clone feature predate scenarios?

**Comment by knu** [comment]
One could easily remove preset scenarios if one wanted, so I think it'd be fine to merge this.

**Comment by cantino** [comment]
I'm comfortable with this.  Thanks @thiagotalma!

**Pull request merged**
