### PR TITLE
updated hash syntax to Ruby 1.9

### PR DESCRIPTION
**Pull request by askl56**

### CODE REVIEW

**Comment by cantino** [comment]
Hey @askl56, thanks!

I'm hesitant to merge this, as it will change the `git blame` history for a large portion of the codebase.  My general approach is to update portions of the code as they are touched.

**Comment by askl56** [comment]
Fair enough chief, no worries, just thought I'd help.

**Comment by cantino** [comment]
It's appreciated!

@knu / @dsander, do you agree that we should migrate to this over time?  If not, I'm happy to merge.

**Comment by dsander** [comment]
> I'm hesitant to merge this, as it will change the git blame history for a large portion of the codebase. My general approach is to update portions of the code as they are touched.

I agree.

**Comment by cantino** [comment]
Thanks again @askl56, I appreciate you taking the time!

**Pull request closed without merging**
