### PR TITLE
Access site with invalid SSL

### PR DESCRIPTION
**Pull request by vitorbaptista**
This is a pull request to implement the functionality described in https://github.com/cantino/huginn/issues/648. This is still lacking docs. As there're no docs on the WebRequestConcern itself (AFAIK), we'll need to document the `disable_ssl_verification` on all agent that implements this concern.

Is it right, @cantino? Is there a better way? Apart from the docs, any thoughts on this PR?

### CODE REVIEW

**Comment by KimJungHun** [comment]
@vitorbaptista Hello

**Comment by KimJungHun** [comment]
@vitorbaptista Thank you for your implement. I also need to use "disable_ssl_verification" option for faraday.

**Comment by KimJungHun** [comment]
@vitorbaptista Thank you for your implement. I also need to use "disable_ssl_verification" option for faraday. :)

**Comment by cantino** [comment]
I should have merged this a while ago!  Merged.

**Comment by vitorbaptista** [comment]
@cantino I'm sorry I'm taking too long to answer your and @knu's suggestions. Life didn't allow me much time to work on this.

I'm happy this is merged now, although it could be improved. I can't say that I'll be able to fix the rough edges, but if I have some free time and someone else haven't fixed it yet, I'll take a look.

Thanks again for the great software.

**Comment by cantino** [comment]
No worries at all. If you want to send a PR that just updates the description text for the agents that use the WebRequestConcern so people know about your feature, that's the only thing I'd suggest.

**Comment by cantino** [comment]
Actually, don't worry about it, I'll just update the docs.

**Pull request merged**
