### PR TITLE
Add a variable `_loop_` for use in `template`

### PR DESCRIPTION
**Pull request by knu**
This allows user to do many things.  For example, you can add "index/total" to the messages of a series of updates found in a check.  You can embed a special value in the last event created from a page so you can make a downstream agent perform something just once per an update of the page.

### CODE REVIEW

**Comment by cantino** [comment]
I think this is a good idea.  Since the info for this agent is getting so long, do you think we should break some it out as links to wiki pages?

**Comment by knu** [comment]
> wonder if we could use this other places as well.

We could probably add this feature to the SortableEvents concern as an option to append a `_loop_` key to each emitted event.  It could be named something like `include_loop_info` and global to all agents.  Does that sound good?

**Comment by knu** [comment]
If we include the variable in an event, having keys other than `index` and `length` may be just redundant, and the name `_loop_` may not fit.

**Comment by knu** [comment]
Maybe `"sort_info": { "position": 2, "count": 5 }`?

**Comment by cantino** [comment]
The new PR makes sense.  Does it replace this?

**Pull request closed without merging**
