### PR TITLE
Update roles to the current recipe names so that 'vagrant up' works out of the box.

### PR DESCRIPTION
**Pull request by elijah**
This broke for me on a fresh checkout - I'm a huginn noob but I know what Chef likes.  ;-)

Updating to the current nodejs::recipe name makes things work for this part of the 'vagrant up' process again.

### CODE REVIEW

**Comment by cantino** [comment]
Thanks @elijah!

Did everything else work for you?  We were just discussing removing the Chef deployment, since it's not being actively maintained.  However, if it otherwise worked for you, we can keep it.

**Comment by cantino** [comment]
Eg #694

**Comment by elijah** [comment]
Yes, it seems to be fine after those two changes.  I can probably spend
some cycles on it periodically - these were easy fixes.

Just getting started with huginn, mostly because I want things that IFTTT
doesn't have integrations for.  ;-)

--e

**Comment by cantino** [comment]
@elijah, great, I'll keep it around then and see if I can get the Vagrant file to work.  Thanks!

**Pull request merged**
