### PR TITLE
no implicit conversion of nil into string

### PR DESCRIPTION
**Pull request by Jngai**

### CODE REVIEW

**Comment by Jngai** [comment]
I was getting no implicit conversion of nil into string bug error. Without `to_s`, `job.handler `comes back to be `nil`.

**Comment by dsander** [comment]
Nice, that makes sense. Do you remember when the exception happened?

**Comment by Jngai** [comment]
I remember I was actually deleting agents and didn't have any left. Then I clicked on job management and pop up an error page. After I solved the problem there were queued jobs left.

**Comment by dsander** [comment]
Interesting that this never happened to anyone before, thanks for fixing it!

**Comment by Jngai** [comment]
I fly through the app while testing locally. The way I work can bring up quirks..... hehe

**Pull request merged**
