### PR TITLE
update twitter and twitter-stream for the secuity issue in the http gem

### PR DESCRIPTION
**Pull request by cantino**

### CODE REVIEW

**Comment by cantino** [comment]
The TwitterUserAgent and TwitterStreamAgent both still seem to be working for me.  Can someone else double check too?

**Comment by dsander** [comment]
Any particular reason for the update? I think you mentioned somewhere the native twitter gem now has support for the streaming api? If we utilize that we could get rid of `twitter_stream` which seems not to be maintained anymore.

**Comment by cantino** [comment]
The `http` and `rest-client` gems have security issues:

* OSVDB-119927
* OSVDB-119878

**Comment by dsander** [comment]
:+1: Worked for me too.

**Comment by cantino** [comment]
Thanks :smile:

**Pull request merged**
