### PR TITLE
Fix the PORT for issue #895

### PR DESCRIPTION
**Pull request by ianblenke**

### CODE REVIEW

**Comment by dsander** [comment]
Looks good to me :+1:

**Comment by cantino** [comment]
Go ahead and merge @ianblenke :)

**Comment by ianblenke** [comment]
I'll have to login as @icblenke, as @ianblenke doesn't have commit access. We should definitely switch commit access over to @ianblenke going forward.

**Comment by cantino** [comment]
@icblenke @ianblenke Sorry about that, I'm switching it to @ianblenke now.

**Pull request merged**
