### PR TITLE
Adding square icon and iOS assets

### PR DESCRIPTION
**Pull request by willyg302**
All necessary assets in the `media/iOS` directory.

### CODE REVIEW

**Comment by cantino** [comment]
Thanks @willyg302!  Do you have any interest in also wiring the logo through the Rails app, like on the dashboard page?

**Comment by willyg302** [comment]
Sure I could take a look at it!

**Comment by knu** [comment]
Thanks!  I'll do the apple-touch-icon part.

**Comment by knu** [comment]
Just pushed #835.

**Comment by willyg302** [comment]
Login page design WIP is below, please let me know your thoughts.

Also for the main dash, do you want to keep the quote and image of Odin or remove?

huginn-login

**Comment by cantino** [comment]
Nice!  Maybe more padding above and below the image, and it could be a bit smaller.  I'm open to changes on the main dash too, if you have ideas.

**Pull request merged**
