### PR TITLE
Protect the latest event from automatic deletion when using MySQL

### PR DESCRIPTION
**Pull request by knu**
This is a workaround for #1940.

### CODE REVIEW

**Comment by cantino** [comment]
Awesome! How do we test this?

**Comment by knu** [comment]
@cantino Forgot to add the spec.  I'll see if it passes on both MySQL and PostgreSQL on Travis.

**Comment by cantino** [comment]
Hey @jplitza, @knu has a potential fix for the issue you found in #1940.  Would you be in a situation where you could test and see if it fixes the issue?

**Comment by jplitza** [comment]
Well, in theory, yes. But it would take me a while, both for deploying the fix and for verifying its intended effect (because, as mentioned in #1940, this is a low volume server 😉).

**Comment by dsander** [comment]
👍 Looks like a good fix for the most common cause for the issue.

**Comment by cantino** [comment]
Well, this makes sense to me too @knu. Looks good.

**Comment by Maroo-b** [comment]
👍

**Pull request merged**
