### PR TITLE
Update celluloid and delayed_job to avoid potential memory issues

### PR DESCRIPTION
**Pull request by cantino**
Hopefully address @wasafiri's feedback in https://github.com/cantino/huginn/issues/978#issuecomment-171506643.

### CODE REVIEW

**Comment by wasafiri** [comment]
It's unclear that delayed_job 4.1.0 resolves the memory issue reported. I suggest reverting to version 4.0.5.

**Comment by cantino** [comment]
Given your edit, do we need to upgrade DJ at all?

**Comment by wasafiri** [comment]
No.

**Comment by cantino** [comment]
On the other hand, is there any harm in upgrading? :smile:

**Comment by dsander** [comment]
The `delayed_job` changelog looks harmless and `celluloid` is only used in development, so I guess it should be fine :+1:

**Pull request merged**
