### PR TITLE
Use non-optimized DelayedJob reserve sql strategy

### PR DESCRIPTION
**Pull request by dsander**
Fixes sql deadlocks when running many quick jobs with multiple workers

Deadlocks happened when DJ was trying to delete finished jobs from the database, as a result those jobs where run a second time which created duplicate event.

Adresses #977

Thanks to @mavenlink and @cantino for the fix in `delayed_job_active_record`

### CODE REVIEW

**Comment by cantino** [comment]
LGTM.  Thanks @dsander!  This is mostly thinks to https://github.com/collectiveidea/delayed_job_active_record/pull/111.  I added you as a maintainer on the fork in case you ever need it.

**Comment by klausmeyer** [comment]
Maybe you could give a up-vote (:+1:) in https://github.com/collectiveidea/delayed_job_active_record/pull/111 to increase the probability getting it merged?

**Comment by cantino** [comment]
Done :)  Thanks for making it!

**Comment by klausmeyer** [comment]
Thanks. You're welcome.

**Comment by cantino** [comment]
I think we can re-point this at master now since collectiveidea/delayed_job_active_record#111 has been merged.  I'll make a PR.

**Pull request merged**
