### PR TITLE
Adding logo and media files

### PR DESCRIPTION
**Pull request by willyg302**
In `media/` directory. Also replaced `public/favicon.ico` and modified readme to include new logo at top.

### CODE REVIEW

**Comment by cantino** [comment]
Awesome!  I'm trying to decide if a lighter colored headset would help, like in #592.

**Comment by willyg302** [comment]
This is a tad lighter:

huginn-logo

As for merging, that's entirely up to you :laughing: The current font seemed to work best out of a lot that I tried, but if you have any fonts you like (other logos that happen to catch your eye are a great source of inspiration for this) just let me know and I'll experiment!

**Comment by cantino** [comment]
I think I liked this one's headset color: https://github.com/cantino/huginn/issues/592#issuecomment-82055448

**Comment by willyg302** [comment]
You're talking about the black and white headset?

huginn-logo copy

**Comment by cantino** [comment]
Yea, I think I prefer this coloring.  What do other people thing?

**Comment by willyg302** [comment]
It does make the eye and red feather stand out more.

@knu @m7md88 @dsander @alias1 @chriseidhof @virtadpt @space-pope @KeithHanson @crawfordcomeaux @urnf @armish @snicker @deanputney Thoughts?

**Comment by alias1** [comment]
It feels better with the overall image, but I wonder if there isn't enough contrast between the headset and bird now, particularly at small sizes.

**Comment by space-pope** [comment]
I think I'm with the crowd on this one—specifically, @cantino's concern about the font and @alias1's about the contrast at small sizes. I do like this color scheme, though; my only addition to the feedback so far would be that having "Huginn" in that shade of gray makes the name of the software look deemphasized, much like you'd see on a disabled button in a dialog box. Could we maybe try switching the colors on the name and the tagline?

**Comment by dsander** [comment]
I really like the colors of the latest version, and don't think that the low contrast between the headset and the bird is a problem. Especially at the small sizes the raven should be the identifying element.

How do you feel about the yellow background of the small images? I think I would like a less 'alerting' color better.

**Comment by alias1** [comment]
Maybe drop the headset on the smallest icons?




I'd be up for trying colours other than the yellow.



—

**Comment by cantino** [comment]
I think the headset is important to keep.

**Comment by willyg302** [comment]
Muted the yellow a bit. Since our color scheme is now leaning towards grays and reds/oranges, I colored the font orange. Also changed up the font to something with a bit more bite. Feel free to check out [this list](http://www.awwwards.com/the-100-greatest-free-fonts-for-2014.html) for some font ideas if this still doesn't work.

rect3593-5

**Comment by space-pope** [comment]
I like the changes. The orange on white is a bit harsh to my eyes, but I'm one of those people who keeps all their editors with a black background. This probably wouldn't be displayed in too big a sea of white anyway. You shouldn't have given me a list of font options, though, because now I'm wondering what either a Canaro or Gentona italic face would look like :).

**Comment by alias1** [comment]
+1 for orange on white is a bit retina burning (creature of the night
here), but as above, I assume we wouldn't actually have it on a stark white
background very often/at all maybe?

**Comment by willyg302** [comment]
Well, probably the most visible use of the logo now would be the GitHub readme which is on white. And putting that on a background would be quite odd.

@space-pope haha, sadly both Canaro and Gentona seem to be free for personal use only and the licenses are outrageous. If I can find a knockoff of either tho, I'll definitely see how it looks.

**Comment by cantino** [comment]
@willyg302 I really like the new look!

**Comment by willyg302** [comment]
@cantino Great! Updated the PR.

**Comment by cantino** [comment]
Awesome!  Merging.  We can always iterate more from here.

**Comment by cantino** [comment]
Looks great in the readme :)

**Comment by willyg302** [comment]
Yup, just ping me if there are any issues or other formats/media you need. Thanks!

**Pull request merged**
