### PR TITLE
Use ActiveJobs interface

### PR DESCRIPTION
**Pull request by dsander**
I was surprised how little changes were needed, hope I did not miss anything. When this is merged it should be pretty easy to support both delayed_job or sidekiq.

### CODE REVIEW

**Comment by cantino** [comment]
Wow, that's really simple!  Nicely done.  It's working well for you?

We'd need to update `WorkerStatusController` too before we could switch to sidekiq.

**Comment by dsander** [comment]
I just ran the tests and a few minutes in development, can't test it in
production at the moment because I am still waiting for the object
allocation spike to happen again.

When running sidekiq I would replace our worker status controller with
sidekiq-web.

**Comment by cantino** [comment]
I'll merge this into my deployment and let it run for a bit.

**Comment by dsander** [comment]
Great, I have been running it for about two days now and did not experience any issues.

**Comment by cantino** [comment]
Seems good to me so far as well.

**Comment by knu** [comment]
Cool.  Let me note that you have to make sure all agents in use are made thread-safe before you can switch to Sidekiq.

**Comment by dsander** [comment]
@knu Is that an issue when we are running on MRI?

**Comment by knu** [comment]
@dsander I'm afraid so.  DelayedJob is single-threaded and forks a new process for each worker that only runs one job at a time, which means no memory is shared among simultaneously running agents.  So, even if an agent instance carelessly used a process-global storage (such as class variables and class instance variables) to keep track of its states that would never affect other simultaneously running agents.  However, it would become a problem in Sidekiq because it runs many agents in parallel with memory shared. (Fortunately, Agent instances are not shared because they are instantiated by `Agent.find(agent_id)` for each agent run)
On MRI, I/O is under GVL and not multiplexed, but in other parts there will always be a context switch.

**Comment by dsander** [comment]
Right, that makes sense, I also read some of the gems we use are not thread safe or are known to [cause trouble](https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting) with sidekiq which might be a deal breaker :disappointed:

**Comment by cantino** [comment]
This has been working fine for me.

**Comment by dsander** [comment]
Great, for me too. Thanks for double checking!

**Pull request merged**
