### PR TITLE
Ignore the fixture API key in WeatherAgent

### PR DESCRIPTION
**Pull request by cantino**
Allow default WeatherAgent to be valid and savable even without a valid API key.

### CODE REVIEW

**Comment by dsander** [comment]
Is the change needed for the specs to run properly? If that's the case I think it should either be changed in the fixtures or stubbed in the specs.

**Comment by cantino** [comment]
I created a new instance with seed data and the WeatherAgent isn't valid by default.  It probably should be?

**Comment by dsander** [comment]
Good question, the `WeatherAgent` needs a valid API key work properly right? If that's the case I think it's fine to be not valid otherwise it would run, fail and create failed jobs.

**Comment by cantino** [comment]
It shouldn't run or appear working? with this change, but also will allow
the user to save it. Maybe it's not needed-- I just didn't like that I
couldn't save it at all without a key.

**Comment by dsander** [comment]
I was under the impression that we do not run Agents that are invalid, but that does not seem to be the case. Looks good to me 😄

**Comment by cantino** [comment]
Yea, that might be a good fix too.

**Pull request merged**
