### PR TITLE
Send the value of the optional unfurl_links option to Slack. 

### PR DESCRIPTION
**Pull request by sillygwailo**
Addresses #892.

### CODE REVIEW

**Comment by cantino** [comment]
I assume nothing bad happens if `unfurl_links` isn't provided?

**Comment by sillygwailo** [comment]
I assume that too, but I'll actually test it.

-- 
Richard Eriksson
justagwailo.com

**Comment by sillygwailo** [comment]
No adverse effects of not including `unfurl_links` as a property in the agent. It just sends the URL to Slack without unfurling it, and Huginn doesn't complain.

**Comment by cantino** [comment]
Thanks for double checking! :)  Merging now.

**Pull request merged**
