### PR TITLE
allow the webhook agent to loop over returned results if the payload_path points to an array

### LINKED ISSUE #764: JSONPath help
Hi I have a webhook agent receiving post but the payload is blank. I think it has to do with the payload_path not being correct. Below is the raw data that is being posted, can someone help me with the path I need to put to get the payload. I am trying to get the title, description, location and date. 

{"name":"Hill","count":69,"frequency":"Daily","version":12,"newdata":true,"lastrunstatus":"partial","lastsuccess":"Sun Mar 29 2015 19:10:48 GMT+0000 (UTC)","thisversionstatus":"partial","nextrun":"Mon Mar 30 2015 19:10:48 GMT+0000 (UTC)","thisversionrun":"Sun Mar 29 2015 19:10:48 GMT+0000 (UTC)","results":{"collection1":[{"title":{"text"some title"","href"http:// link""},"description":"1 2 3 4 5 6 7 8 9","location":"1 2 3 4 5 6 7 8 9","date":{"text":"1 2 3 4 5 6 7 8 9","href":"javascript:__doPostBack('DataGrid1$_ctl1$_ctl1','')"},"url":"http://ng.com"},{"title":{"text"some title 2015"","href"http://2.com""},"description"descriptionsome"Job Type","location":"Location","date":{"text":"Post Date*","href":"javascript:__doPostBack('DataGrid1$_ctl2$_ctl0','')"},"url":"http://nn.com"},{"title":{"text":"APB","href":"http://n.com"},"description":"Temporary","location":"IN - Indiana","date":{"text":"03/27/2015","href":""},"url":"http://jcom"}

### PR DESCRIPTION
**Pull request by cantino**
Should fix #764

### CODE REVIEW

**Comment by cantino** [comment]
Mind giving a quick code review @dsander?

**Comment by dsander** [comment]
The code looks good. I am wondering if the change would break existing consumers of WebHookAgents. Maybe add a migration that checks for existing WebHookAgent events that include an array and display a warning?

**Comment by cantino** [comment]
I thought about that, but when I tried making a spec where `payload_path` pointed at an array, I got an error saying that event payloads must be an object, so I don't think anyone could have had that working before.

**Comment by dsander** [comment]
Ok, Cool!

**Pull request merged**
