### PR TITLE
Updating public transport agent

### PR DESCRIPTION
**Pull request by Jngai**

### CODE REVIEW

**Comment by cantino** [comment]
Assuming these changes worked for you, they're very much appreciated!  Where is the other broken link?

**Comment by Jngai** [comment]
The other broken link doesn't exist. I was copying the url from the app into the browser and didn't notice that there was a snippet of regular expression in the string. I added a little snippet of extra information to make the direction more explicit. I just recognized now that you bold up the "N" but didn't see it in the past.

**Comment by Jngai** [comment]
I think this is overtly complicated http://webservices.nextbus.com/service/publicXMLFeed?command=agencyList

**Comment by cantino** [comment]
`http://www.nextbus.com/predictor/adaStop.jsp?a=sf-muni&r=N` isn't working for me, though.  Is it working for you?

**Comment by Jngai** [comment]
Some stop predictor works and some doesn't. I am just using it to show the tags. However it may be misleading. I think those links are the most updated interactive links given from nextbus though. If I can't find a replacement then maybe I can try switching it out with nextbus given xml feed.

**Comment by cantino** [comment]
The fixes at the top are definitely needed.

Maybe add after `copy the part of the URL after "r=".` something like.  `(The link may not work, but we're just trying to get the part after the r=, so even if it gives an error, continue to the next step.)`?

**Comment by Jngai** [comment]
I added the clarification.

**Comment by cantino** [comment]
Thanks @Jngai!

**Pull request merged**
