### PR TITLE
replace delayed_job queue methods with ActiveJob counterparts

### PR DESCRIPTION
**Pull request by brianpetro**
discussed here https://github.com/cantino/huginn/issues/1412

### CODE REVIEW

**Comment by cantino** [comment]
This looks right to me.

Was this sufficient for resque to work for you?

**Comment by brianpetro** [comment]
@cantino Yes.

**Comment by dsander** [comment]
Neat, looks good to me too. I think it's ok to not document the additional steps needed for now because it would require significant work on the installation guides.

**Comment by cantino** [comment]
Looks great, thanks!

**Pull request merged**
