### PR TITLE
Simplify the log format for Dry Run

### PR DESCRIPTION
**Pull request by knu**
- Omit the severity initial and progname
- Show the elapsed time in HH:MM:SS instead of full date-time

### CODE REVIEW

**Comment by knu** [comment]
Idea taken from #1371 by @thiagotalma.

**Comment by cantino** [comment]
Maybe `@dry_run_started_at` if it'll bleed out of the dry_run as an instance variable.  Otherwise, looks good to me!

**Comment by knu** [comment]
Good point, I renamed it and got this PR merged, thanks!

**Comment by thiagotalma** [comment]
@knu What do you think of even more dry?

```
[00:00:00] [INFO] Dry Run started
[00:00:00] [INFO] Fetching https://graph.facebook.com/.....
```

**Pull request merged**
